### ISSUE TITLE
何かしらのアクションをしているときにファントムが来ないようにする

### ISSUE THREAD

**Issue by ekuinox** [mcymze/IntegrativeYmzeServerPlugin#2]

**Comment by ekuinox** [comment]
ゾンビ肉食ったら一定Tickこねえようにしま～す

**Comment by takkatha10** [comment]
青くなったジャガイモでも同じ効果得られるようにして❤

**Comment by ekuinox** [comment]
> 青くなったジャガイモでも同じ効果得られるようにして❤
![image](https://user-images.githubusercontent.com/3678413/74489880-14799100-4f0a-11ea-91c2-3843ba42ee0a.png)
